# Generated by Django 5.0.1 on 2025-07-19 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['year', 'current_rank']},
        ),
        migrations.AddField(
            model_name='brand',
            name='year',
            field=models.PositiveIntegerField(default=2025, help_text='Year this ranking data applies to'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('slug', 'year')},
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['year', 'current_rank'], name='brands_bran_year_090b39_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['year', 'slug'], name='brands_bran_year_fe2814_idx'),
        ),
    ]
