# Generated by Django 5.0.1 on 2025-07-19 02:25

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Data title', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('data_type', models.CharField(choices=[('market_size', 'Market Size'), ('growth_rate', 'Growth Rate'), ('market_share', 'Market Share'), ('consumer_spending', 'Consumer Spending'), ('brand_awareness', 'Brand Awareness'), ('customer_satisfaction', 'Customer Satisfaction')], max_length=30)),
                ('value', models.CharField(help_text='Data value', max_length=50)),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement', max_length=20)),
                ('period', models.CharField(help_text="Time period (e.g., '2024 Q1')", max_length=50)),
                ('source', models.CharField(blank=True, help_text='Data source', max_length=200)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False, help_text='Data verified by research team')),
                ('confidence_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
            ],
            options={
                'verbose_name': 'Market Data',
                'verbose_name_plural': 'Market Data',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchMethodology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('methodology_type', models.CharField(choices=[('quantitative', 'Quantitative'), ('qualitative', 'Qualitative'), ('mixed', 'Mixed Methods')], max_length=30)),
                ('sample_size_min', models.PositiveIntegerField(blank=True, null=True)),
                ('sample_size_max', models.PositiveIntegerField(blank=True, null=True)),
                ('data_collection_methods', models.TextField(blank=True)),
                ('analysis_techniques', models.TextField(blank=True)),
                ('limitations', models.TextField(blank=True)),
                ('peer_reviewed', models.BooleanField(default=False)),
                ('industry_standard', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Research Methodology',
                'verbose_name_plural': 'Research Methodologies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='SEO description', max_length=300)),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO keywords', max_length=500)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('shares_count', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(help_text='Insight title', max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('description', models.TextField(help_text='Short description', max_length=500)),
                ('content', ckeditor.fields.RichTextField(help_text='Full insight content')),
                ('insight_type', models.CharField(choices=[('market_analysis', 'Market Analysis'), ('consumer_behavior', 'Consumer Behavior'), ('brand_performance', 'Brand Performance'), ('industry_trends', 'Industry Trends'), ('methodology', 'Methodology'), ('forecast', 'Forecast')], default='market_analysis', max_length=30)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='insights/images/')),
                ('featured_image_alt', models.CharField(blank=True, max_length=200)),
                ('report_file', models.FileField(blank=True, help_text='PDF report file', null=True, upload_to='insights/reports/')),
                ('research_team', models.CharField(blank=True, help_text='Research team members', max_length=200)),
                ('data_points', models.CharField(blank=True, help_text="Number of data points (e.g., '50K+')", max_length=20)),
                ('accuracy', models.CharField(blank=True, help_text="Accuracy percentage (e.g., '94%')", max_length=10)),
                ('sample_size', models.CharField(blank=True, help_text="Sample size (e.g., '10,000')", max_length=20)),
                ('regions_covered', models.CharField(blank=True, help_text="Regions covered (e.g., '36 States')", max_length=50)),
                ('is_premium', models.BooleanField(default=False, help_text='Premium content requiring subscription')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured insight')),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Number of downloads')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
            ],
            options={
                'verbose_name': 'Insight',
                'verbose_name_plural': 'Insights',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsightDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_email', models.EmailField(blank=True, help_text='User email for tracking', max_length=254)),
                ('user_name', models.CharField(blank=True, max_length=100)),
                ('user_company', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('download_type', models.CharField(choices=[('pdf', 'PDF Report'), ('data', 'Raw Data'), ('summary', 'Executive Summary')], default='pdf', max_length=20)),
                ('insight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='insights.insight')),
            ],
            options={
                'verbose_name': 'Insight Download',
                'verbose_name_plural': 'Insight Downloads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsightKeyFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finding', models.CharField(help_text='Key finding statement', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Detailed explanation')),
                ('impact_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('insight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_findings', to='insights.insight')),
            ],
            options={
                'ordering': ['insight', 'order'],
            },
        ),
        migrations.CreateModel(
            name='InsightMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text='Metric label', max_length=100)),
                ('value', models.CharField(help_text='Metric value', max_length=50)),
                ('change', models.CharField(blank=True, help_text='Change from previous period', max_length=20)),
                ('trend', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('stable', 'Stable')], default='stable', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('insight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='insights.insight')),
            ],
            options={
                'ordering': ['insight', 'order', 'label'],
                'unique_together': {('insight', 'label')},
            },
        ),
    ]
