# Generated by Django 5.0.1 on 2025-07-19 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='year',
            field=models.PositiveIntegerField(default=2025, help_text='Year this insight applies to'),
        ),
    ]
